heat_template_version: 2015-10-15

description: Simple template to deploy a single compute instance.

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for compute instance
    default: trusty-server-cloudimg-amd64-disk1.img 
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used
    default: m1.small
  key:
    type: string
    label: Key name
    description: Name of key-pair to be used for compute instance
    

  network:
    type: string
    label: Private network name or ID/public network name or ID.
    description: Network to attach instance to.
    default: private

resources:
  cloud_config:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        write_files:
        - path: /tmp/file
          content: "This is a basic Cloud-config example."

  my_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key }
      networks:
        - network: { get_param: network }
      user_data_format: RAW
      user_data: {get_resource: cloud_config}

outputs:
  instance_ip:
    description: IP address of the instance
    value: { get_attr: [my_instance, first_address] }


